name: Enhancement Proposal
description: Fill this form out with your proposal.
title: "[Enhancement Proposal]: "
labels: ["enhancement_proposal"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: In 1 or 2 sentences, summarize the purpose of your proposed change.
      placeholder: Type here
    validations:
      required: true
  - type: textarea
    id: specification
    attributes:
      label: Specification
      description: Describe the change you would like to see.
      placeholder: Type here
    validations:
      required: true
  - type: textarea
    id: motication
    attributes:
      label: Motivation
      description: Why would this change be beneficial?
      placeholder: Type here
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Show examples of this change being used.
      placeholder: Type here
    validations:
      required: true
  - type: textarea
    id: alternativesConsidered
    attributes:
      label: Alternatives Considered
      description: Did you consider another way to solve this issue?
      placeholder: Type here
    validations:
      required: false
  - type: textarea
    id: references
    attributes:
      label: References
      description: Put links to any resources you used or we that would be helpful for us to look at in regard to this change.
      placeholder: Type here
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/iheartla/iheartla/blob/master/code_of_conduct.md)
      options:
        - label: I agree to follow the Code of Conduct
          required: true
